apiVersion: v1
kind: Service
metadata:
  name: capa-annotator-metrics
  namespace: capa-annotator-system
  labels:
    app.kubernetes.io/name: capa-annotator
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: capa-annotator
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: capa-annotator
    app.kubernetes.io/component: controller
